model:
  api_base: 
  api_key: 
  # deployment_name: gpt-35-turbo-16k # -32k
  deployment_name: gpt-4-32k # -32k
  api_type: openai
  api_version: '2024-02-01' 
  # MODEL_NAME: gpt-4-32k

# model:
#   RESOURCE_ENDPOINT: 
#   api_base: 
#   api_key: 
#   deployment_name: chatgpt432k
#   api_type: openai
#   api_version: '2024-02-01' 
#   # MODEL_NAME: gpt-4-32k

embedding_model:
  api_base: 
  api_key: 
  deployment_name: text-embedding-3-small # sentence-transformers/all-mpnet-base-v2
  api_type: openai #huggingface
  api_version: '2024-02-01' 

data:
  documents_dir: data/md/soybean
  ontology_path: data/ontology/farm_cropcultivation_schema_ontology_jsonld.json
  kg_storage_path: data/kg/soybean_32768
  index_dir: index/vector_soybean
  subdir: False
  smart_pdf: True
  chunk_size: 20000
  
query:
  method: ontohypergraph-rag #kg-rag
  batch_size: 10
  hyperparams: 
    top_k: 20
  mode: json
  questions_file: 
    - data/md/soybean/questions/ragas/testset_10_0p0,0p0,1p0.csv 
    - data/md/soybean/questions/ragas/testset_10_0p0,1p0,0p0.csv 
    - data/md/soybean/questions/ragas/testset_10_0p5,0p25,0p25.csv 
    - data/md/soybean/questions/ragas/testset_10_0p25,0p5,0p25.csv 
    - data/md/soybean/questions/ragas/testset_10_0p25,0p25,0p5.csv 
    - data/md/soybean/questions/ragas/testset_10_1p0,0p0,0p0.csv
  answers_file: results/soybean/new_ragas_answers_ontohypergraphrag.json

question_generator:
  framework: ragas
  test_size: 10
  distr: 
    simple: 1.0
    reasoning: 0.0
    multi_context: 0.0 

evaluator:
  eval_file: results/soybean/new_ragas_answers_ontohypergraphrag_top_k20.json
  reference_free: True
  type: single
  metrics: 
    - answer_correctness
    - faithfulness
    - answer_similarity
    - answer_relevancy
